trigger:
  - master
  - dev

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday run
    branches:
      include:
        - master
    always: true

pool:
  vmImage: "ubuntu-latest"

variables:
  GO111MODULE: "on"
  SPAUTH_CI: "true"

steps:
  - task: GoTool@0
    displayName: "Install Go"
    inputs:
      version: "1.19"

  - script: |
      go version
      go get ./...
    displayName: "Restore dependencies"
    workingDirectory: "$(System.DefaultWorkingDirectory)"

  - script: |
      go test ./auth/... -race -coverprofile=auth_coverage.out -covermode=atomic
    displayName: "Run auth tests"
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    env:
      SPAUTH_SITEURL: $(ci.spo.siteurl)
      SPAUTH_USERNAME: $(ci.spo.username)
      SPAUTH_PASSWORD: $(ci.spo.password)
      SPAUTH_CLIENTID: $(ci.spo.clientid)
      SPAUTH_CLIENTSECRET: $(ci.spo.clientsecret)

  - script: |
      go test ./ -v -count=1 -coverprofile=gosip_coverage.out -covermode=atomic && \
      go test ./cpass/... -v -race -count=1 -coverprofile=cpass_coverage.out -covermode=atomic && \
      go test ./csom/... -v -race -count=1 -coverprofile=csom_coverage.out -covermode=atomic
    displayName: "Run util tests"
    workingDirectory: "$(System.DefaultWorkingDirectory)"

  - script: |
      go test ./api/... -v -race -count=1 -coverprofile=api_coverage.out -covermode=atomic
    displayName: "Run API tests"
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    env:
      SPAUTH_ENVCODE: spo
      SPAPI_HEAVY_TESTS: true
      GOMAXPROCS: 10
      ENV_SPO_SITEURL: $(ci.spo.siteurl)
      ENV_SPO_USERNAME: $(ci.spo.username)
      ENV_SPO_PASSWORD: $(ci.spo.password)
      GOSIP_TESTS_WEBHOOKS_URL: $(ci.spo.notificationsUrl)

  - script: |
      bash ./test/scripts/cover-merge.sh
      bash <(curl -s https://codecov.io/bash)
    displayName: "Publish code coverage"
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    env:
      CODECOV_TOKEN: $(ci.codecov.token)
